# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# BASIC
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://royvn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: nl_NL

authors:
  royvn:
    name: Roy van Neden
    image: /uploads/royvn.jpg
    email: roy.van.neden@gmail.com
    web: http://roy.vanneden.nl
    twitter: royvn_
    github: royvn
    instagram: royvn
    linkedin: https://www.linkedin.com/in/roy-van-neden-10549761/

# SEO
logo: 
title: Roy van Neden
description: Designer & developer uit Leidschendam woonachtig in Den Haag.
permalink: pretty

# How many articles do you wish to appear on the front page:
# paginate: 3

# COLLECTIONS
collections:
  posts:
    output: true
    permalink: /blog/:title/
  projects:
    output: true
    permalink: /projecten/:title/

# BUILD
markdown: kramdown
highlighter: rouge

plugins: 
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - src
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - package-lock.json
  - package.json
  - postcss.config.js
  - node_modules
  - README.md